name: "Synchronize locales"
permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:

jobs:
  sync-with-transifex:
    uses: ./.github/workflows/transifex-sync.yml
    secrets:
      github-token: "${{ secrets.LOCALES_SYNC_TOKEN }}"
      transifex-token: "${{ secrets.TRANSIFEX_TOKEN }}"
