name: "Transifex sync"

on:
  workflow_call:
    secrets:
      transifex-token:
        required: true
      github-token:
        required: true

jobs:
  transifex-sync:
    name: "Sync locales with Transifex"
    runs-on: "ubuntu-latest"
    steps:

    - name: "Checkout"
      uses: "actions/checkout@v4"

    - name: "Install system dependencies"
      run: |
        sudo apt-get update --quiet
        sudo apt-get install gettext libgettextpo-dev python3-dev python3-pip libffi-dev libxml2-dev libxslt-dev git
        pip install lxml gitpython PyGithub termcolor

    - name: "Install composer dependencies"
      uses: "php-actions/composer@v6"
      with:
        dev: yes

    - name: "Extract locales"
      run: |
        ./vendor/bin/extract-locales

    - name: "Push source file"
      uses: "transifex/cli-action@v2"
      with:
        args: "push"
        token: "${{ secrets.transifex-token }}"

    - name: "Clean tmp directory"
      run: |
        rm -fr /tmp/tx

    - name: "Pull translations"
      uses: "transifex/cli-action@v2"
      with:
        args: "pull --all --minimum-perc=80 --overwrite"
        token: "${{ secrets.transifex-token }}"


    - name: "Compile MO files"
      run: |
        ./vendor/bin/plugin-release --compile-mo

    - name: "Check status"
      id: "check-status"
      # en_GB.mo file will always be considered as updated as it is regenerated by the ./vendor/bin/extract-locales command.
      # It have to be ignore to prevent "empty" PRs to be generated.
      run: |
        if [[ `git status --porcelain locales/*.mo ':(exclude)locales/en_GB.mo'` ]]; then
          echo "CREATE_PR=yes" >> $GITHUB_OUTPUT
        else
          echo "CREATE_PR=no" >> $GITHUB_OUTPUT
        fi

    - name: "Create pull request"
      if: ${{ steps.check-status.outputs.CREATE_PR == 'yes' }}
      uses: "peter-evans/create-pull-request@v7"
      with:
        commit-message: "Update locales"
        branch: "i18n-updates"
        branch-suffix: "timestamp"
        add-paths: "locales/"
        labels: "i18n"
        delete-branch: true
        title: "Chore(i18n): update translations"
        body: "Auto-updated translations files"
        # A PAT is required.
        # From https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow:
        # > When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN,
        # > with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run.
        # > This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes
        # > code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository
        # > contains a workflow configured to run when push events occur.
        token: ${{ secrets.github-token }}
