name: "Transifex sync"

on:
  workflow_call:
    secrets:
      transifex-token:
        required: true
      github-token:
        required: true

jobs:
  transifex-sync:
    name: "Sync locales with Transifex"
    runs-on: "ubuntu-latest"
    steps:

    - name: "Checkout"
      uses: "actions/checkout@v4"

    - name: "Install system dependencies"
      run: |
        sudo apt-get update --quiet
        sudo apt-get install gettext libgettextpo-dev python3-dev python3-pip libffi-dev libxml2-dev libxslt-dev git
        pip install lxml gitpython PyGithub termcolor

    - name: "Install composer dependencies"
      uses: "php-actions/composer@v6"
      with:
        dev: yes

    - name: "Extract locales"
      run: |
        ./vendor/bin/extract-locales

    - name: "Push source file"
      uses: "transifex/cli-action@v2"
      with:
        args: "push"
        token: "${{ secrets.transifex-token }}"

    - name: "Clean tmp directory"
      run: |
        rm -fr /tmp/tx

    - name: "Pull translations"
      uses: "transifex/cli-action@v2"
      with:
        args: "pull -a --minimum-perc=80 --overwrite"
        token: "${{ secrets.transifex-token }}"

    - name: "Compile MO files"
      run: |
        ./vendor/bin/plugin-release --compile-mo

    - name: "Check status"
      id: "check-status"
      run: |
        if [[ `git status --porcelain locales/*.mo ':(exclude)locales/en_GB.mo'` ]]; then
          echo "CREATE_PR=yes" >> $GITHUB_OUTPUT
        else
          echo "CREATE_PR=no" >> $GITHUB_OUTPUT
        fi

    - name: "Create pull request"
      if: ${{ steps.check-status.outputs.CREATE_PR == 'yes' }}
      uses: "peter-evans/create-pull-request@v7"
      with:
        commit-message: "Update locales"
        branch: "i18n-updates"
        branch-suffix: "timestamp"
        add-paths: "locales/"
        labels: "i18n"
        delete-branch: true
        title: "Chore(i18n): update translations"
        body: "Auto-updated translations files"
        token: ${{ secrets.github-token }}
